### PR TITLE
Exatn visitor impl

### PR DESCRIPTION
**Pull request by tnguyen-ornl**
Base implementation of the ExaTN visitor backend (direct simulation mode):

- Retrieve expectation value (Z basis) when a measurement is specified.

- Cache randomized bit measurement result to the acceleration buffer.

- Support multi-shot simulation.

Tested by: unit tests in ExatnMPSVisitorTester.cpp

### CODE REVIEW

**Comment by amccaskey** [comment]
A few things I see that need to be addressed on this PR:

* EXATENSOR_ROOT -> EXATN_DIR
* as is `if(EXATN_DIR)` will not handle paths like `~/.exatn`, only `$HOME/.exatn`
* we should rename ExatnMPSVisitor to ExatnDirectVisitor (with name() = exatn) or something like that, as we are directly contracting the circuit and not decomposing the wavefunction as an MPS. We will make a separate visitor for the MPS algorithm (with name() = exatn-mps).

**Comment by amccaskey** [comment]
I am also unable to get the following script to converge to -1.74 at theta = .59

```python
import xacc,sys, numpy as np
xacc.set_verbose(True)

qpu = xacc.getAccelerator('tnqvm', {'tnqvm-visitor':'exatn-mps'})
buffer = xacc.qalloc(2)

ham = xacc.getObservable('pauli', '5.907 - 2.1433 X0X1 - 2.1433 Y0Y1 + .21829 Z0 - 6.125 Z1')

xacc.qasm('''.compiler xasm
.circuit ansatz2
.parameters t0
.qbit q
X(q[0]);
Ry(q[1],t0);
CX(q[1],q[0]);
''')
ansatz2 = xacc.getCompiled('ansatz2')
opt = xacc.getOptimizer('nlopt', {'nlopt-maxeval':50})

vqe = xacc.getAlgorithm('vqe', {
                        'ansatz': ansatz2,
                        'accelerator': qpu,
                        'observable': ham,
                        'optimizer': opt
                        })
vqe.execute(buffer)
```

One thing I notice is that if we don't specify shots, then buffer.appendMeasurement gets called once. This causes AcceleratorBuffer::getExpectationValueZ() to compute the expectation value based on the single measurement result instead of just returning exp-val-z.

**Comment by tnguyen-ornl** [comment]
I've implemented those recommendations in https://github.com/ORNL-QCI/tnqvm/pull/24/commits/645360e4d47abe8ddb25b674983155e7159a2415

Also, the `exp-val-z` calculation has been revised to match that of the ITensor backend. I've tested with both the H2 and H3 examples and got E = -1.74886 and E = -2.04482, respectively.

**Comment by amccaskey** [comment]
Thanks, this looks good!

**Pull request merged**
